### ISSUE TITLE
Call to undefined function PhpXmlRpc\each()

### ISSUE THREAD

**Issue by salmanm2003** [pkp/plagiarism#39]
@asmecher I have noticed that this plugin is not fully compatible with PHP 8 regarding the outdated phpXmlRpc library.
I can send a PR to solve this.

**Comment by asmecher** [comment]
@salmanm2003 I would welcome a PR, thanks! Could you describe the issue here, i.e. do you get an error message? That'll help others find this if they encounter the same problem.

**Comment by asmecher** [comment]
That makes sense, @salmanm2003; assigning to you for a PR, thanks!

**Comment by salmanm2003** [comment]
@asmecher I have already sent a PR for this issue: https://github.com/pkp/plagiarism/pull/40

**Comment by asmecher** [comment]
Thanks, @salmanm2003, I've merged that for `main`. I'm presuming you've tried it against `stable-3_3_0`, right? Shall I cherry-pick it there?

**Comment by salmanm2003** [comment]
Thanks @asmecher,
Yes, I have tested it against `stable-3_3_0` as it is compatible with PHP8.
Not sure what you mean by cherry-pick it there, as `main` is the only branch I know that we use usually, the rest are kinda outdated?

**Comment by asmecher** [comment]
We keep parallel branches of the plugins we maintain to go with the branches of OJS/OMP/OPS. So there will usually be a `stable-3_3_0` for 3.3.0-x releases of OJS, and a `main` for release in the next major release (3.4.0 in this case), etc.

I've cherry-picked the commit back to `stable-3_3_0`, thanks!

**Comment by ctgraham** [comment]
This appears to be resolve to me, and I'll include it in a new release; please re-open if not fully resolved.
